################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
F2837xD_Adc.obj: C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/source/F2837xD_Adc.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2837xD_CodeStartBranch.obj: C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/source/F2837xD_CodeStartBranch.asm $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2837xD_CpuTimers.obj: C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/source/F2837xD_CpuTimers.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2837xD_DefaultISR.obj: C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/source/F2837xD_DefaultISR.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2837xD_Dma.obj: C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/source/F2837xD_Dma.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2837xD_GlobalVariableDefs.obj: C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/source/F2837xD_GlobalVariableDefs.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2837xD_Gpio.obj: C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/source/F2837xD_Gpio.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2837xD_Ipc_Driver_Lite.obj: C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/source/F2837xD_Ipc_Driver_Lite.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2837xD_PieCtrl.obj: C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/source/F2837xD_PieCtrl.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2837xD_PieVect.obj: C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/source/F2837xD_PieVect.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2837xD_SysCtrl.obj: C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/source/F2837xD_SysCtrl.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

F2837xD_usDelay.obj: C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/source/F2837xD_usDelay.asm $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c28xx_board.obj: C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw/MW_c28xx_board.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c28xx_csl.obj: C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw/MW_c28xx_csl.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c28xx_pwm.obj: C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw/MW_c28xx_pwm.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_data.obj: C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw/MW_data.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

c2837xDBoard_Realtime_Support.obj: C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src/c2837xDBoard_Realtime_Support.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

c2837xDSchedulerTimer0.obj: C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src/c2837xDSchedulerTimer0.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ert_main.obj: C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw/ert_main.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

profiler_Support.obj: C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src/profiler_Support.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

rtGetInf.obj: C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw/rtGetInf.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

rtGetNaN.obj: C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw/rtGetNaN.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

rt_nonfinite.obj: C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw/rt_nonfinite.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

testboard.obj: C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw/testboard.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

testboard_data.obj: C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw/testboard_data.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/bin/cl2000" --include_path="C:/Users/ThinkPad/Downloads/ti-cgt-c2000_16.9.2.LTS/include" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE" --include_path="C:/Users/ThinkPad/Desktop/MBDCODE/testboard_ert_rtw" --include_path="C:/Program Files/MATLAB/R2018b/extern/include" --include_path="C:/Program Files/MATLAB/R2018b/simulink/include" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2018b/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/supportpackages/tic2000/src" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_headers/include" --include_path="C:/TI/controlSUITE/device_support/F2837xD/v190/F2837xD_common" --include_path="C:/Program Files/MATLAB/R2018b/toolbox/rtw/targets/common/can/blocks/tlc_c" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2018b/toolbox/target/shared/externalmode_daemon/include" --define=MODEL=testboard --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=MW_PIL_SCIFIFOLEN=16 --define=F2837X_REG_FORMAT --define=MW_F2837XD --define=STACK_SIZE=512 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F28377D --define=CPU1 --define=BOOT_FROM_FLASH=0 -s -v28 -ml  --large_memory_model --silicon_version=28 --define=LARGE_MODEL -v28 --float_support=fpu32 -ml -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 -DF28377D -DCPU1 -DBOOT_FROM_FLASH=0 --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


